/**
 * The written half of the training section: one prose page per technique, and
 * the one-line summary the index lists it with.
 *
 * The prose is ours (decision 18). Each file follows sudokuoftheday.com's
 * definition of the technique — the same definition `packages/sudoku-core/src/
 * techniques/<id>.ts` implements, which matters because the practise examples
 * are generated by that code and would otherwise teach a different technique
 * from the one the page describes — and cites the site as a reference. None of
 * their text is copied.
 *
 * The imports are static and explicit rather than an `import.meta.glob`: a glob
 * would make a missing page a runtime `undefined` on the technique's own page,
 * whereas a missing file here fails the build.
 */

import type { TechniqueId } from 'sudoku-core';

import candidateLines from './prose/candidateLines.md?raw';
import doublePairs from './prose/doublePairs.md?raw';
import forcingChains from './prose/forcingChains.md?raw';
import hiddenPair from './prose/hiddenPair.md?raw';
import hiddenQuad from './prose/hiddenQuad.md?raw';
import hiddenSingle from './prose/hiddenSingle.md?raw';
import hiddenTriple from './prose/hiddenTriple.md?raw';
import multipleLines from './prose/multipleLines.md?raw';
import nakedPair from './prose/nakedPair.md?raw';
import nakedQuad from './prose/nakedQuad.md?raw';
import nakedSingle from './prose/nakedSingle.md?raw';
import nakedTriple from './prose/nakedTriple.md?raw';
import swordfish from './prose/swordfish.md?raw';
import xWing from './prose/xWing.md?raw';

/** The explanation shown on a technique's "Explain" tab. */
export const PROSE: Readonly<Record<TechniqueId, string>> = {
  nakedSingle,
  hiddenSingle,
  candidateLines,
  doublePairs,
  multipleLines,
  nakedPair,
  hiddenPair,
  nakedTriple,
  hiddenTriple,
  xWing,
  forcingChains,
  nakedQuad,
  hiddenQuad,
  swordfish,
};

/** One line each, for the index. Short enough to scan the whole ladder. */
export const SUMMARIES: Readonly<Record<TechniqueId, string>> = {
  nakedSingle: 'A square with only one candidate left must take it.',
  hiddenSingle: 'A digit with only one place left in a unit goes there.',
  candidateLines: 'A digit confined to one line inside a box comes off that line elsewhere.',
  doublePairs: 'Two boxes with two places each take two lines of a band between them.',
  multipleLines: 'Two boxes confined to two lines of a band push the third box onto the last one.',
  nakedPair: 'Two squares holding the same two digits own them both.',
  hiddenPair: 'Two digits confined to the same two squares clear everything else out of them.',
  nakedTriple: 'Three squares between them holding only three digits own all three.',
  hiddenTriple: 'Three digits confined to the same three squares clear those squares.',
  xWing: 'A digit twice-placed in two rows, aligned in two columns, clears those columns.',
  forcingChains: 'Both values of a two-candidate square force the same digit somewhere else.',
  nakedQuad: 'Four squares between them holding only four digits own all four.',
  hiddenQuad: 'Four digits confined to the same four squares clear those squares.',
  swordfish: 'An X-Wing one line wider: three rows covering three columns.',
};
